### ISSUE TITLE
What license is Hyperschedule under?  

### ISSUE THREAD

**Issue by TiloRC** [raxod502/hyperschedule#198]
Would it be okay to fork this repo and start a new website?

I would be interested in making a tool geared towards helping people find classes that satisfy general area requirements and fit other criteria such as time of day. You could solve this sort of constraint problem by framing it right and giving it to a SAT or SMT solver. 

However, I'm not really all that interested in the UI side of things and would probably, at least at first, focus on making something for Pomona rather than all the 5C.

**Comment by mia1024** [comment]
We are currently developing a new version of Hyperschedule and having a SAT solver is one of our envisioned features down the line. We would very much appreciate it if you can contribute to the Hyperschedule source instead of forking it. 

As for the general area requirements, we recently gained access to data about exactly which areas a course would satisfy. However, we have not yet integrated this new data into the UI. If you are willing to contribute, can you email me (mceleste@g.hmc.edu) so we can discuss in more details?

**Comment by mia1024** [comment]
0905813
